service: rs-cart-api

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  profile: Viktar_Belski
  stage: v3

functions:
  main:
    handler: dist/main.handler
    events:
      - httpApi:
          method: ANY
          path: /
      - httpApi:
          method: ANY
          path: '/{proxy+}'
